apiVersion: v1
kind: ConfigMap
metadata:
  name: skillio-app-config
  namespace: skillio-prod
  labels:
    app.kubernetes.io/name: skillio-ai
data:
  POSTGRES_SERVER: "skillio-db-headless"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "ai_recruitment"
  STORAGE_TYPE: "local"
  LOCAL_STORAGE_DIR: "/app/storage"
  TEMP_UPLOAD_DIR: "/app/uploads"
  VITE_API_URL: "http://skillio-backend-svc:8000"
---
apiVersion: v1
kind: Secret
metadata:
  name: skillio-db-credentials
  namespace: skillio-prod
  labels:
    app.kubernetes.io/name: skillio-ai
type: Opaque
stringData:
  POSTGRES_USER: "skillio_k8s_user"
  POSTGRES_PASSWORD: "Sk1ll10SecurePass2026"
  SECRET_KEY: "adecdc538394bf726ce03e15cd39eaf1461c4cfc7a4757d15a3d7b29d1df952c"