from pydantic import BaseModel, Field
from typing import List, Optional
from pydantic import UUID4
from datetime import datetime

# These models define the structure of job postings created by HR admins

class JobBase(BaseModel): # contains the core job details
    title: str = Field(..., min_length=3, max_length=255, description="The official title of the public administration role.")
    description: str = Field(..., min_length=10, description="Full description of the role.")
    company_name: str = Field(..., description="E.g., Ministry of Health, City Council.")
    location: str = Field(..., description="Physical location or Remote.")
    requirements: List[str] = Field(default_factory=list, description="General skills or requirements (e.g., Python, SQL).")
    mandatory_criteria: List[str] = Field(default_factory=list, description="Strict requirements (e.g., Bachelor's Degree, Security Clearance).")

class JobCreate(JobBase):
    pass
    # We do NOT ask the HR Admin to input an 'embedding' array or 'creator_id'.
    # creator_id will be extracted from their JWT token.
    # embedding will be generated by the AI service on the backend.

class JobUpdate(BaseModel):
    title: Optional[str] = Field(None, min_length=3, max_length=255)
    description: Optional[str] = Field(None, min_length=10)
    company_name: Optional[str] = None
    location: Optional[str] = None
    requirements: Optional[List[str]] = None
    mandatory_criteria: Optional[List[str]] = None

class JobResponse(JobBase):
    id: UUID4
    creator_id: Optional[UUID4] = None
    created_at: datetime
    # We purposely omit the 'embedding' from the response. 
    # Sending an array of 1536 floats to the frontend is a huge waste of bandwidth

    class Config:
        from_attributes = True
